[package]
name = "ghostnet-rs"
version = "0.0.1-alpha"
edition = "2024"

[[bin]]
name = "ghostnet-rs"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"] }
rustls = "0.23.31"
rustls-native-certs = "0.8.1"
rustls-pki-types = "1.12.0"
